Repository systopia/de.systopia.eck, pull requests merged in 2023-11, with the labels that each got.

#91 Add missing search_fields metadata
  Civi/Eck/API/Entity.php
Labels: bug

#94 Fix display of option fields in entity view
  CRM/Eck/Page/Entity/View.php
Labels: enhancement, status:reviewed and tested

#95 Switch to using `ng-href` over `href` attribute for avoiding bugs with `hook_civicrm_alterAngular()` implementations
  templates/ang/afsearch_eck_listing.tpl
Labels: bug, status:needs review

#97 Administering subtypes should only be allowed with the "administer CiviCRM" permission
  xml/Menu/eck.xml
Labels: bug, status:needs review

#98 Convert navigation menu item definition to managed entities
  eck.php
  managed/Navigation__eck_entities.mgd.php
Labels: enhancement, status:reviewed and tested
