Repository systopia/de.systopia.eck, pull requests merged in 2023-07, with the labels that each got.

#80 Make ECK APIv4 entities a "DAOEntity" type
  Civi/Eck/API/Entity.php
Labels: bug, status:needs review

#81 Add test assertion that api reports correct table_name
  tests/phpunit/api/v4/EckEntity/EckEntityTest.php
Labels: enhancement, status:needs review

#82 Make ECK entity types export- and revertable as managed entities
  Civi/Api4/EckEntityType.php
Labels: enhancement, status:reviewed and tested

#83 Use subtype value instead of name for afform routes as they may not contain UTF-8 characters
  CRM/Eck/Page/Entity.php
  Civi/Api4/Service/Spec/Provider/EckEntityTypeSpecProvider.php
  Civi/Eck/API/Entity.php
  templates/ang/afsearch_eck_listing.tpl
Labels: bug, status:needs review

#86 Restrict entity type names to 52 characters to (really) fit the 64 characters length limit of MySQL table names
  CRM/Eck/DAO/EckEntityType.php
  CRM/Eck/Upgrader.php
  eck.php
  sql/auto_install.sql
  sql/auto_uninstall.sql
  xml/schema/CRM/Eck/EckEntityType.xml
Labels: enhancement, status:reviewed and tested
