Repository systopia/de.systopia.eck, pull requests merged in 2024-07, with the labels that each got.

#135 Update PHPUnit Tests to specify covers attribute and convert phpunit xml dist to be phpunit9 supported
  phpunit.xml.dist
  tests/phpunit/api/v4/EckEntity/EckEntityTest.php
Labels: enhancement, status:needs review

#137 Copy missing core function
  Civi/Api4/Service/Spec/Provider/EckEntitySpecProvider.php
Labels: bug, status:needs review

#140 Use Afform's automatic custom blocks for custom fields on ECK entity forms
  Civi/Eck/API/Entity.php
  info.xml
  templates/ang/afformEck.tpl
Labels: enhancement, status:reviewed and tested
