Repository systopia/de.systopia.eck, pull requests merged in 2025-06, with the labels that each got.

#159 Afform - Skip fetching layout if not needed
  Civi/Eck/API/Entity.php
Labels: enhancement

#162 Do not attempt to query ECK entity types when the table does not yet exist
  .github/workflows/phpunit.yml
  CRM/Eck/BAO/EckEntityType.php
  phpstan.neon.dist
  tests/docker-compose.yml
  tests/phpunit/api/v4/EckEntity/EckEntityTest.php
Labels: bug, status:needs review

#165 [1.0.x] Do not attempt to query ECK entity types when the table does not yet exist
  .github/workflows/phpunit.yml
  CRM/Eck/BAO/EckEntityType.php
  phpstan.neon.dist
  tests/docker-compose.yml
  tests/phpunit/api/v4/EckEntity/EckEntityTest.php
Labels: bug, status:reviewed and tested

#161 Add support for exporting entities from created EntityTypes
  Civi/Api4/EckEntity.php
Labels: feature, status:reviewed and tested

#166 [1.0.x] Add support for exporting entities from created EntityTypes
  Civi/Api4/EckEntity.php
Labels: feature, status:reviewed and tested

#167 Manually delete option value in `cg_extend_objects` option group when deleting entity types
  CRM/Eck/BAO/EckEntityType.php
Labels: bug, status:reviewed and tested

#168 Update docs/text to make it clearer that subtype is required
  README.md
  managed/SavedSearch_ECK_Entity_Types.mgd.php
  templates/CRM/Eck/Form/EntityType.tpl
Labels: documentation, status:needs work

#171 [1.0.x] Update translation template and translations
  CRM/Eck/DAO/Entity.php
  CRM/Eck/Page/Entity.php
  CRM/Eck/Page/Entity/View.php
  l10n/de_DE/LC_MESSAGES/eck.mo
  l10n/de_DE/LC_MESSAGES/eck.po
  l10n/eck.pot
Labels: enhancement, status:reviewed and tested

#172 Make created_id and modified_id available to FormBuilder for display/filtering (readonly)
  CRM/Eck/DAO/Entity.php
Labels: enhancement, status:reviewed and tested

#173 Make created_id and modified_id available to FormBuilder for display/filtering (readonly)
  CRM/Eck/DAO/Entity.php
Labels: enhancement, status:reviewed and tested
