Repository systopia/de.systopia.eck, pull requests merged in 2025-03, with the labels that each got.

#148 Remove deprecated afform properties
  Civi/Eck/API/Entity.php
Labels: enhancement, status:reviewed and tested

#149 REF - use str_starts_with instead of strpos
  CRM/Eck/BAO/Entity.php
Labels: enhancement, status:reviewed and tested

#147 Move post hook to run after custom data is saved
  CRM/Eck/DAO/Entity.php
Labels: bug, status:reviewed and tested

#152 Raise core version compatibility to 5.73 as of #127 and #136
  ci/composer.json
  info.xml
Labels: bug

#151 Add PHPStan baseline for ignoring errors in code that is to be refactored
  phpstan-baseline.neon
  phpstan.ci.neon
  phpstan.neon.dist
  phpstan.neon.template
Labels: enhancement, status:reviewed and tested

#153 Add PHPStan baseline
  Civi/Api4/EckEntity.php
  phpstan-baseline.neon
  phpstan.ci.neon
  phpstan.neon.dist
  phpstan.neon.template
Labels: bug, status:needs review

#154 Single entity view: Prepare TabHeader tabs for changed core template
  CRM/Eck/Page/Entity/TabHeader.php
Labels: bug, status:reviewed and tested

#155 [1.0.x backport] Single entity view: Prepare TabHeader tabs for changed core template
  CRM/Eck/Page/Entity/TabHeader.php
Labels: bug, status:reviewed and tested
